### ISSUE TITLE
Oracle implementation does not work

### ISSUE THREAD

**Issue by agnesetaluzzi** [aarontognoli/SWENG2-LearnLib-ResearchProject#2]
Tried with the random walk approach but the oracle does not find a counterexample: the queries are apparently too short even if I modify the lookahead field, or if I implement an equal on Domus records including the timestamp and id of the sensor, it just runs infinite membership queries.

If I try to implement the equivalence oracle with a SampleEQOracle (giving it directly the queries I want to try), it just finds one counterexample and then it blocks forever. If I give it only the preTea() sequences of records, it just gives out an automata with one nonfinal state (this is the only way for now to make the experiment finish).

**Comment by aarontognoli** [comment]
I think i fixed the problems, need more testing
I committed the result of the first test (one day one user)
I think we can pull on main this milestone
